language: node_js
node_js:
  - "0.8"
  - "0.10"
before_install:
  - gem update --system
  - gem install sass --version "=3.2.12"
  - gem install compass --version "=0.12.2"
  - npm install -g grunt-cli
